// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: api/pb/mail/mail.proto

package mail

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MailboxMessageStatus int32

const (
	MailboxMessageStatus_UNSPECIFIED MailboxMessageStatus = 0
	MailboxMessageStatus_ALL         MailboxMessageStatus = 1
	MailboxMessageStatus_READ        MailboxMessageStatus = 2
	MailboxMessageStatus_UNREAD      MailboxMessageStatus = 3
)

// Enum value maps for MailboxMessageStatus.
var (
	MailboxMessageStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ALL",
		2: "READ",
		3: "UNREAD",
	}
	MailboxMessageStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ALL":         1,
		"READ":        2,
		"UNREAD":      3,
	}
)

func (x MailboxMessageStatus) Enum() *MailboxMessageStatus {
	p := new(MailboxMessageStatus)
	*p = x
	return p
}

func (x MailboxMessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailboxMessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pb_mail_mail_proto_enumTypes[0].Descriptor()
}

func (MailboxMessageStatus) Type() protoreflect.EnumType {
	return &file_api_pb_mail_mail_proto_enumTypes[0]
}

func (x MailboxMessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailboxMessageStatus.Descriptor instead.
func (MailboxMessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{0}
}

type ArchiveRetrievalStatus int32

const (
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_UNSPECIFIED  ArchiveRetrievalStatus = 0
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_QUEUED       ArchiveRetrievalStatus = 1
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_EXECUTING    ArchiveRetrievalStatus = 2
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_MOVETOBUCKET ArchiveRetrievalStatus = 3
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_FAILED       ArchiveRetrievalStatus = 4
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_CANCELED     ArchiveRetrievalStatus = 5
	ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_SUCCESS      ArchiveRetrievalStatus = 6
)

// Enum value maps for ArchiveRetrievalStatus.
var (
	ArchiveRetrievalStatus_name = map[int32]string{
		0: "ARCHIVE_RETRIEVAL_STATUS_UNSPECIFIED",
		1: "ARCHIVE_RETRIEVAL_STATUS_QUEUED",
		2: "ARCHIVE_RETRIEVAL_STATUS_EXECUTING",
		3: "ARCHIVE_RETRIEVAL_STATUS_MOVETOBUCKET",
		4: "ARCHIVE_RETRIEVAL_STATUS_FAILED",
		5: "ARCHIVE_RETRIEVAL_STATUS_CANCELED",
		6: "ARCHIVE_RETRIEVAL_STATUS_SUCCESS",
	}
	ArchiveRetrievalStatus_value = map[string]int32{
		"ARCHIVE_RETRIEVAL_STATUS_UNSPECIFIED":  0,
		"ARCHIVE_RETRIEVAL_STATUS_QUEUED":       1,
		"ARCHIVE_RETRIEVAL_STATUS_EXECUTING":    2,
		"ARCHIVE_RETRIEVAL_STATUS_MOVETOBUCKET": 3,
		"ARCHIVE_RETRIEVAL_STATUS_FAILED":       4,
		"ARCHIVE_RETRIEVAL_STATUS_CANCELED":     5,
		"ARCHIVE_RETRIEVAL_STATUS_SUCCESS":      6,
	}
)

func (x ArchiveRetrievalStatus) Enum() *ArchiveRetrievalStatus {
	p := new(ArchiveRetrievalStatus)
	*p = x
	return p
}

func (x ArchiveRetrievalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArchiveRetrievalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pb_mail_mail_proto_enumTypes[1].Descriptor()
}

func (ArchiveRetrievalStatus) Type() protoreflect.EnumType {
	return &file_api_pb_mail_mail_proto_enumTypes[1]
}

func (x ArchiveRetrievalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArchiveRetrievalStatus.Descriptor instead.
func (ArchiveRetrievalStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From      string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Body      []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt    int64  `protobuf:"varint,7,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Message) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

// to email or to thread
type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread        string `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"` // sender's thread.ID and did.Token
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`         // pub key of receiver
	ToBody        []byte `protobuf:"bytes,3,opt,name=to_body,json=toBody,proto3" json:"to_body,omitempty"`
	ToSignature   []byte `protobuf:"bytes,4,opt,name=to_signature,json=toSignature,proto3" json:"to_signature,omitempty"`
	FromBody      []byte `protobuf:"bytes,5,opt,name=from_body,json=fromBody,proto3" json:"from_body,omitempty"`
	FromSignature []byte `protobuf:"bytes,6,opt,name=from_signature,json=fromSignature,proto3" json:"from_signature,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *SendMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMessageRequest) GetToBody() []byte {
	if x != nil {
		return x.ToBody
	}
	return nil
}

func (x *SendMessageRequest) GetToSignature() []byte {
	if x != nil {
		return x.ToSignature
	}
	return nil
}

func (x *SendMessageRequest) GetFromBody() []byte {
	if x != nil {
		return x.FromBody
	}
	return nil
}

func (x *SendMessageRequest) GetFromSignature() []byte {
	if x != nil {
		return x.FromSignature
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMessageResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListInboxMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread    string               `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Seek      string               `protobuf:"bytes,2,opt,name=seek,proto3" json:"seek,omitempty"`
	Limit     int64                `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Ascending bool                 `protobuf:"varint,4,opt,name=ascending,proto3" json:"ascending,omitempty"`
	Status    MailboxMessageStatus `protobuf:"varint,5,opt,name=status,proto3,enum=api.pb.mail.MailboxMessageStatus" json:"status,omitempty"`
}

func (x *ListInboxMessagesRequest) Reset() {
	*x = ListInboxMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInboxMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxMessagesRequest) ProtoMessage() {}

func (x *ListInboxMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListInboxMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{3}
}

func (x *ListInboxMessagesRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *ListInboxMessagesRequest) GetSeek() string {
	if x != nil {
		return x.Seek
	}
	return ""
}

func (x *ListInboxMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInboxMessagesRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

func (x *ListInboxMessagesRequest) GetStatus() MailboxMessageStatus {
	if x != nil {
		return x.Status
	}
	return MailboxMessageStatus_UNSPECIFIED
}

type ListInboxMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ListInboxMessagesResponse) Reset() {
	*x = ListInboxMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInboxMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxMessagesResponse) ProtoMessage() {}

func (x *ListInboxMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListInboxMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{4}
}

func (x *ListInboxMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListSentboxMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread    string               `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Seek      string               `protobuf:"bytes,2,opt,name=seek,proto3" json:"seek,omitempty"`
	Limit     int64                `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Ascending bool                 `protobuf:"varint,4,opt,name=ascending,proto3" json:"ascending,omitempty"`
	Status    MailboxMessageStatus `protobuf:"varint,5,opt,name=status,proto3,enum=api.pb.mail.MailboxMessageStatus" json:"status,omitempty"`
}

func (x *ListSentboxMessagesRequest) Reset() {
	*x = ListSentboxMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSentboxMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSentboxMessagesRequest) ProtoMessage() {}

func (x *ListSentboxMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSentboxMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListSentboxMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ListSentboxMessagesRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *ListSentboxMessagesRequest) GetSeek() string {
	if x != nil {
		return x.Seek
	}
	return ""
}

func (x *ListSentboxMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSentboxMessagesRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

func (x *ListSentboxMessagesRequest) GetStatus() MailboxMessageStatus {
	if x != nil {
		return x.Status
	}
	return MailboxMessageStatus_UNSPECIFIED
}

type ListSentboxMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ListSentboxMessagesResponse) Reset() {
	*x = ListSentboxMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSentboxMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSentboxMessagesResponse) ProtoMessage() {}

func (x *ListSentboxMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSentboxMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListSentboxMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{6}
}

func (x *ListSentboxMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ReadInboxMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread string `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadInboxMessageRequest) Reset() {
	*x = ReadInboxMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadInboxMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadInboxMessageRequest) ProtoMessage() {}

func (x *ReadInboxMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadInboxMessageRequest.ProtoReflect.Descriptor instead.
func (*ReadInboxMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{7}
}

func (x *ReadInboxMessageRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *ReadInboxMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadInboxMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadAt int64 `protobuf:"varint,1,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
}

func (x *ReadInboxMessageResponse) Reset() {
	*x = ReadInboxMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadInboxMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadInboxMessageResponse) ProtoMessage() {}

func (x *ReadInboxMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadInboxMessageResponse.ProtoReflect.Descriptor instead.
func (*ReadInboxMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{8}
}

func (x *ReadInboxMessageResponse) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

type DeleteInboxMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread string `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteInboxMessageRequest) Reset() {
	*x = DeleteInboxMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInboxMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInboxMessageRequest) ProtoMessage() {}

func (x *DeleteInboxMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInboxMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteInboxMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInboxMessageRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *DeleteInboxMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteInboxMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteInboxMessageResponse) Reset() {
	*x = DeleteInboxMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInboxMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInboxMessageResponse) ProtoMessage() {}

func (x *DeleteInboxMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInboxMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteInboxMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{10}
}

type DeleteSentboxMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread string `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSentboxMessageRequest) Reset() {
	*x = DeleteSentboxMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSentboxMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSentboxMessageRequest) ProtoMessage() {}

func (x *DeleteSentboxMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSentboxMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteSentboxMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSentboxMessageRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

func (x *DeleteSentboxMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSentboxMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSentboxMessageResponse) Reset() {
	*x = DeleteSentboxMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSentboxMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSentboxMessageResponse) ProtoMessage() {}

func (x *DeleteSentboxMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSentboxMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteSentboxMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{12}
}

type ArchivesLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArchivesLsRequest) Reset() {
	*x = ArchivesLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivesLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivesLsRequest) ProtoMessage() {}

func (x *ArchivesLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivesLsRequest.ProtoReflect.Descriptor instead.
func (*ArchivesLsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{13}
}

type ArchivesLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archives []*ArchiveLsItem `protobuf:"bytes,1,rep,name=archives,proto3" json:"archives,omitempty"`
}

func (x *ArchivesLsResponse) Reset() {
	*x = ArchivesLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivesLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivesLsResponse) ProtoMessage() {}

func (x *ArchivesLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivesLsResponse.ProtoReflect.Descriptor instead.
func (*ArchivesLsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{14}
}

func (x *ArchivesLsResponse) GetArchives() []*ArchiveLsItem {
	if x != nil {
		return x.Archives
	}
	return nil
}

type ArchiveLsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid  string                   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Info []*ArchiveLsItemMetadata `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *ArchiveLsItem) Reset() {
	*x = ArchiveLsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveLsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveLsItem) ProtoMessage() {}

func (x *ArchiveLsItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveLsItem.ProtoReflect.Descriptor instead.
func (*ArchiveLsItem) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{15}
}

func (x *ArchiveLsItem) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ArchiveLsItem) GetInfo() []*ArchiveLsItemMetadata {
	if x != nil {
		return x.Info
	}
	return nil
}

type ArchiveLsItemMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DealId uint64 `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
}

func (x *ArchiveLsItemMetadata) Reset() {
	*x = ArchiveLsItemMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveLsItemMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveLsItemMetadata) ProtoMessage() {}

func (x *ArchiveLsItemMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveLsItemMetadata.ProtoReflect.Descriptor instead.
func (*ArchiveLsItemMetadata) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{16}
}

func (x *ArchiveLsItemMetadata) GetDealId() uint64 {
	if x != nil {
		return x.DealId
	}
	return 0
}

type ArchivesImportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid     string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	DealIds []uint64 `protobuf:"varint,2,rep,packed,name=deal_ids,json=dealIds,proto3" json:"deal_ids,omitempty"`
}

func (x *ArchivesImportRequest) Reset() {
	*x = ArchivesImportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivesImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivesImportRequest) ProtoMessage() {}

func (x *ArchivesImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivesImportRequest.ProtoReflect.Descriptor instead.
func (*ArchivesImportRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{17}
}

func (x *ArchivesImportRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ArchivesImportRequest) GetDealIds() []uint64 {
	if x != nil {
		return x.DealIds
	}
	return nil
}

type ArchivesImportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArchivesImportResponse) Reset() {
	*x = ArchivesImportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivesImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivesImportResponse) ProtoMessage() {}

func (x *ArchivesImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivesImportResponse.ProtoReflect.Descriptor instead.
func (*ArchivesImportResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{18}
}

type ArchiveRetrievalLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArchiveRetrievalLsRequest) Reset() {
	*x = ArchiveRetrievalLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveRetrievalLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRetrievalLsRequest) ProtoMessage() {}

func (x *ArchiveRetrievalLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRetrievalLsRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRetrievalLsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{19}
}

type ArchiveRetrievalLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retrievals []*ArchiveRetrievalLsItem `protobuf:"bytes,1,rep,name=retrievals,proto3" json:"retrievals,omitempty"`
}

func (x *ArchiveRetrievalLsResponse) Reset() {
	*x = ArchiveRetrievalLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveRetrievalLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRetrievalLsResponse) ProtoMessage() {}

func (x *ArchiveRetrievalLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRetrievalLsResponse.ProtoReflect.Descriptor instead.
func (*ArchiveRetrievalLsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{20}
}

func (x *ArchiveRetrievalLsResponse) GetRetrievals() []*ArchiveRetrievalLsItem {
	if x != nil {
		return x.Retrievals
	}
	return nil
}

type ArchiveRetrievalLsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid          string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Status       ArchiveRetrievalStatus `protobuf:"varint,3,opt,name=status,proto3,enum=api.pb.mail.ArchiveRetrievalStatus" json:"status,omitempty"`
	FailureCause string                 `protobuf:"bytes,4,opt,name=failure_cause,json=failureCause,proto3" json:"failure_cause,omitempty"`
	CreatedAt    int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are assignable to RetrievalType:
	//	*ArchiveRetrievalLsItem_NewBucket
	RetrievalType isArchiveRetrievalLsItem_RetrievalType `protobuf_oneof:"retrieval_type"`
}

func (x *ArchiveRetrievalLsItem) Reset() {
	*x = ArchiveRetrievalLsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveRetrievalLsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRetrievalLsItem) ProtoMessage() {}

func (x *ArchiveRetrievalLsItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRetrievalLsItem.ProtoReflect.Descriptor instead.
func (*ArchiveRetrievalLsItem) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{21}
}

func (x *ArchiveRetrievalLsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArchiveRetrievalLsItem) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ArchiveRetrievalLsItem) GetStatus() ArchiveRetrievalStatus {
	if x != nil {
		return x.Status
	}
	return ArchiveRetrievalStatus_ARCHIVE_RETRIEVAL_STATUS_UNSPECIFIED
}

func (x *ArchiveRetrievalLsItem) GetFailureCause() string {
	if x != nil {
		return x.FailureCause
	}
	return ""
}

func (x *ArchiveRetrievalLsItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (m *ArchiveRetrievalLsItem) GetRetrievalType() isArchiveRetrievalLsItem_RetrievalType {
	if m != nil {
		return m.RetrievalType
	}
	return nil
}

func (x *ArchiveRetrievalLsItem) GetNewBucket() *ArchiveRetrievalLsItemNewBucket {
	if x, ok := x.GetRetrievalType().(*ArchiveRetrievalLsItem_NewBucket); ok {
		return x.NewBucket
	}
	return nil
}

type isArchiveRetrievalLsItem_RetrievalType interface {
	isArchiveRetrievalLsItem_RetrievalType()
}

type ArchiveRetrievalLsItem_NewBucket struct {
	NewBucket *ArchiveRetrievalLsItemNewBucket `protobuf:"bytes,6,opt,name=new_bucket,json=newBucket,proto3,oneof"`
}

func (*ArchiveRetrievalLsItem_NewBucket) isArchiveRetrievalLsItem_RetrievalType() {}

type ArchiveRetrievalLsItemNewBucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Private bool   `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *ArchiveRetrievalLsItemNewBucket) Reset() {
	*x = ArchiveRetrievalLsItemNewBucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveRetrievalLsItemNewBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRetrievalLsItemNewBucket) ProtoMessage() {}

func (x *ArchiveRetrievalLsItemNewBucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRetrievalLsItemNewBucket.ProtoReflect.Descriptor instead.
func (*ArchiveRetrievalLsItemNewBucket) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{22}
}

func (x *ArchiveRetrievalLsItemNewBucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArchiveRetrievalLsItemNewBucket) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type ArchiveRetrievalLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ArchiveRetrievalLogsRequest) Reset() {
	*x = ArchiveRetrievalLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveRetrievalLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRetrievalLogsRequest) ProtoMessage() {}

func (x *ArchiveRetrievalLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRetrievalLogsRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRetrievalLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{23}
}

func (x *ArchiveRetrievalLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArchiveRetrievalLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ArchiveRetrievalLogsResponse) Reset() {
	*x = ArchiveRetrievalLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_mail_mail_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveRetrievalLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRetrievalLogsResponse) ProtoMessage() {}

func (x *ArchiveRetrievalLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_mail_mail_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRetrievalLogsResponse.ProtoReflect.Descriptor instead.
func (*ArchiveRetrievalLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_mail_mail_proto_rawDescGZIP(), []int{24}
}

func (x *ArchiveRetrievalLogsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_pb_mail_mail_proto protoreflect.FileDescriptor

var file_api_pb_mail_mail_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x6d, 0x61,
	0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62,
	0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x41, 0x74, 0x22,
	0xbc, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x74, 0x6f, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x5f, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74,
	0x6f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66,
	0x72, 0x6f, 0x6d, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x44,
	0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0xb5, 0x01, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x65, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4d, 0x0a, 0x19,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x1a,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x65, 0x65, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4f, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6e,
	0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e,
	0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x49, 0x6e,
	0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x18, 0x52, 0x65, 0x61,
	0x64, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x41, 0x74, 0x22, 0x43,
	0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x45, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x73, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a,
	0x12, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x73, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x22, 0x59, 0x0a, 0x0d, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x36,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x4c, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x15, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x4c, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x17, 0x0a, 0x07, 0x64, 0x65, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x64, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x15, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x64, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x18,
	0x0a, 0x16, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x1a, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62,
	0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x72, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x73, 0x22, 0x9c, 0x02, 0x0a, 0x16, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x61,
	0x75, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x43, 0x61, 0x75, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x4d, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x4e,
	0x65, 0x77, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x10, 0x0a, 0x0e, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4f, 0x0a, 0x1f, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x73, 0x49, 0x74, 0x65,
	0x6d, 0x4e, 0x65, 0x77, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1c, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x46, 0x0a, 0x14, 0x4d, 0x61, 0x69,
	0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x52, 0x45, 0x41, 0x44, 0x10,
	0x03, 0x2a, 0xac, 0x02, 0x0a, 0x16, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x24,
	0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x49, 0x45, 0x56, 0x41,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56,
	0x45, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x49, 0x45, 0x56, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x41,
	0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x49, 0x45, 0x56, 0x41, 0x4c,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x29, 0x0a, 0x25, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52,
	0x45, 0x54, 0x52, 0x49, 0x45, 0x56, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x4d, 0x4f, 0x56, 0x45, 0x54, 0x4f, 0x42, 0x55, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x03, 0x12, 0x23,
	0x0a, 0x1f, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x49, 0x45,
	0x56, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x04, 0x12, 0x25, 0x0a, 0x21, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52,
	0x45, 0x54, 0x52, 0x49, 0x45, 0x56, 0x41, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x12, 0x24, 0x0a, 0x20, 0x41, 0x52,
	0x43, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x49, 0x45, 0x56, 0x41, 0x4c, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x06,
	0x32, 0xed, 0x04, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x52, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x62, 0x6f, 0x78,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x62, 0x6f, 0x78,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x13, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x74,
	0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x62, 0x6f,
	0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e,
	0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x62, 0x6f, 0x78,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x6d, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x6e, 0x74, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x62, 0x6f, 0x78, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x65, 0x78, 0x74, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x61, 0x69, 0x6c,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pb_mail_mail_proto_rawDescOnce sync.Once
	file_api_pb_mail_mail_proto_rawDescData = file_api_pb_mail_mail_proto_rawDesc
)

func file_api_pb_mail_mail_proto_rawDescGZIP() []byte {
	file_api_pb_mail_mail_proto_rawDescOnce.Do(func() {
		file_api_pb_mail_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pb_mail_mail_proto_rawDescData)
	})
	return file_api_pb_mail_mail_proto_rawDescData
}

var file_api_pb_mail_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_pb_mail_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_pb_mail_mail_proto_goTypes = []interface{}{
	(MailboxMessageStatus)(0),               // 0: api.pb.mail.MailboxMessageStatus
	(ArchiveRetrievalStatus)(0),             // 1: api.pb.mail.ArchiveRetrievalStatus
	(*Message)(nil),                         // 2: api.pb.mail.Message
	(*SendMessageRequest)(nil),              // 3: api.pb.mail.SendMessageRequest
	(*SendMessageResponse)(nil),             // 4: api.pb.mail.SendMessageResponse
	(*ListInboxMessagesRequest)(nil),        // 5: api.pb.mail.ListInboxMessagesRequest
	(*ListInboxMessagesResponse)(nil),       // 6: api.pb.mail.ListInboxMessagesResponse
	(*ListSentboxMessagesRequest)(nil),      // 7: api.pb.mail.ListSentboxMessagesRequest
	(*ListSentboxMessagesResponse)(nil),     // 8: api.pb.mail.ListSentboxMessagesResponse
	(*ReadInboxMessageRequest)(nil),         // 9: api.pb.mail.ReadInboxMessageRequest
	(*ReadInboxMessageResponse)(nil),        // 10: api.pb.mail.ReadInboxMessageResponse
	(*DeleteInboxMessageRequest)(nil),       // 11: api.pb.mail.DeleteInboxMessageRequest
	(*DeleteInboxMessageResponse)(nil),      // 12: api.pb.mail.DeleteInboxMessageResponse
	(*DeleteSentboxMessageRequest)(nil),     // 13: api.pb.mail.DeleteSentboxMessageRequest
	(*DeleteSentboxMessageResponse)(nil),    // 14: api.pb.mail.DeleteSentboxMessageResponse
	(*ArchivesLsRequest)(nil),               // 15: api.pb.mail.ArchivesLsRequest
	(*ArchivesLsResponse)(nil),              // 16: api.pb.mail.ArchivesLsResponse
	(*ArchiveLsItem)(nil),                   // 17: api.pb.mail.ArchiveLsItem
	(*ArchiveLsItemMetadata)(nil),           // 18: api.pb.mail.ArchiveLsItemMetadata
	(*ArchivesImportRequest)(nil),           // 19: api.pb.mail.ArchivesImportRequest
	(*ArchivesImportResponse)(nil),          // 20: api.pb.mail.ArchivesImportResponse
	(*ArchiveRetrievalLsRequest)(nil),       // 21: api.pb.mail.ArchiveRetrievalLsRequest
	(*ArchiveRetrievalLsResponse)(nil),      // 22: api.pb.mail.ArchiveRetrievalLsResponse
	(*ArchiveRetrievalLsItem)(nil),          // 23: api.pb.mail.ArchiveRetrievalLsItem
	(*ArchiveRetrievalLsItemNewBucket)(nil), // 24: api.pb.mail.ArchiveRetrievalLsItemNewBucket
	(*ArchiveRetrievalLogsRequest)(nil),     // 25: api.pb.mail.ArchiveRetrievalLogsRequest
	(*ArchiveRetrievalLogsResponse)(nil),    // 26: api.pb.mail.ArchiveRetrievalLogsResponse
}
var file_api_pb_mail_mail_proto_depIdxs = []int32{
	0,  // 0: api.pb.mail.ListInboxMessagesRequest.status:type_name -> api.pb.mail.MailboxMessageStatus
	2,  // 1: api.pb.mail.ListInboxMessagesResponse.messages:type_name -> api.pb.mail.Message
	0,  // 2: api.pb.mail.ListSentboxMessagesRequest.status:type_name -> api.pb.mail.MailboxMessageStatus
	2,  // 3: api.pb.mail.ListSentboxMessagesResponse.messages:type_name -> api.pb.mail.Message
	17, // 4: api.pb.mail.ArchivesLsResponse.archives:type_name -> api.pb.mail.ArchiveLsItem
	18, // 5: api.pb.mail.ArchiveLsItem.info:type_name -> api.pb.mail.ArchiveLsItemMetadata
	23, // 6: api.pb.mail.ArchiveRetrievalLsResponse.retrievals:type_name -> api.pb.mail.ArchiveRetrievalLsItem
	1,  // 7: api.pb.mail.ArchiveRetrievalLsItem.status:type_name -> api.pb.mail.ArchiveRetrievalStatus
	24, // 8: api.pb.mail.ArchiveRetrievalLsItem.new_bucket:type_name -> api.pb.mail.ArchiveRetrievalLsItemNewBucket
	3,  // 9: api.pb.mail.APIService.SendMessage:input_type -> api.pb.mail.SendMessageRequest
	5,  // 10: api.pb.mail.APIService.ListInboxMessages:input_type -> api.pb.mail.ListInboxMessagesRequest
	7,  // 11: api.pb.mail.APIService.ListSentboxMessages:input_type -> api.pb.mail.ListSentboxMessagesRequest
	9,  // 12: api.pb.mail.APIService.ReadInboxMessage:input_type -> api.pb.mail.ReadInboxMessageRequest
	11, // 13: api.pb.mail.APIService.DeleteInboxMessage:input_type -> api.pb.mail.DeleteInboxMessageRequest
	13, // 14: api.pb.mail.APIService.DeleteSentboxMessage:input_type -> api.pb.mail.DeleteSentboxMessageRequest
	4,  // 15: api.pb.mail.APIService.SendMessage:output_type -> api.pb.mail.SendMessageResponse
	6,  // 16: api.pb.mail.APIService.ListInboxMessages:output_type -> api.pb.mail.ListInboxMessagesResponse
	8,  // 17: api.pb.mail.APIService.ListSentboxMessages:output_type -> api.pb.mail.ListSentboxMessagesResponse
	10, // 18: api.pb.mail.APIService.ReadInboxMessage:output_type -> api.pb.mail.ReadInboxMessageResponse
	12, // 19: api.pb.mail.APIService.DeleteInboxMessage:output_type -> api.pb.mail.DeleteInboxMessageResponse
	14, // 20: api.pb.mail.APIService.DeleteSentboxMessage:output_type -> api.pb.mail.DeleteSentboxMessageResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_pb_mail_mail_proto_init() }
func file_api_pb_mail_mail_proto_init() {
	if File_api_pb_mail_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pb_mail_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInboxMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInboxMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSentboxMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSentboxMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadInboxMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadInboxMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInboxMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInboxMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSentboxMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSentboxMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivesLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivesLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveLsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveLsItemMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivesImportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivesImportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveRetrievalLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveRetrievalLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveRetrievalLsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveRetrievalLsItemNewBucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveRetrievalLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_mail_mail_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveRetrievalLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_pb_mail_mail_proto_msgTypes[21].OneofWrappers = []interface{}{
		(*ArchiveRetrievalLsItem_NewBucket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pb_mail_mail_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_mail_mail_proto_goTypes,
		DependencyIndexes: file_api_pb_mail_mail_proto_depIdxs,
		EnumInfos:         file_api_pb_mail_mail_proto_enumTypes,
		MessageInfos:      file_api_pb_mail_mail_proto_msgTypes,
	}.Build()
	File_api_pb_mail_mail_proto = out.File
	file_api_pb_mail_mail_proto_rawDesc = nil
	file_api_pb_mail_mail_proto_goTypes = nil
	file_api_pb_mail_mail_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	ListInboxMessages(ctx context.Context, in *ListInboxMessagesRequest, opts ...grpc.CallOption) (*ListInboxMessagesResponse, error)
	ListSentboxMessages(ctx context.Context, in *ListSentboxMessagesRequest, opts ...grpc.CallOption) (*ListSentboxMessagesResponse, error)
	ReadInboxMessage(ctx context.Context, in *ReadInboxMessageRequest, opts ...grpc.CallOption) (*ReadInboxMessageResponse, error)
	DeleteInboxMessage(ctx context.Context, in *DeleteInboxMessageRequest, opts ...grpc.CallOption) (*DeleteInboxMessageResponse, error)
	DeleteSentboxMessage(ctx context.Context, in *DeleteSentboxMessageRequest, opts ...grpc.CallOption) (*DeleteSentboxMessageResponse, error)
}

type aPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServiceClient(cc grpc.ClientConnInterface) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/api.pb.mail.APIService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListInboxMessages(ctx context.Context, in *ListInboxMessagesRequest, opts ...grpc.CallOption) (*ListInboxMessagesResponse, error) {
	out := new(ListInboxMessagesResponse)
	err := c.cc.Invoke(ctx, "/api.pb.mail.APIService/ListInboxMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListSentboxMessages(ctx context.Context, in *ListSentboxMessagesRequest, opts ...grpc.CallOption) (*ListSentboxMessagesResponse, error) {
	out := new(ListSentboxMessagesResponse)
	err := c.cc.Invoke(ctx, "/api.pb.mail.APIService/ListSentboxMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ReadInboxMessage(ctx context.Context, in *ReadInboxMessageRequest, opts ...grpc.CallOption) (*ReadInboxMessageResponse, error) {
	out := new(ReadInboxMessageResponse)
	err := c.cc.Invoke(ctx, "/api.pb.mail.APIService/ReadInboxMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteInboxMessage(ctx context.Context, in *DeleteInboxMessageRequest, opts ...grpc.CallOption) (*DeleteInboxMessageResponse, error) {
	out := new(DeleteInboxMessageResponse)
	err := c.cc.Invoke(ctx, "/api.pb.mail.APIService/DeleteInboxMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteSentboxMessage(ctx context.Context, in *DeleteSentboxMessageRequest, opts ...grpc.CallOption) (*DeleteSentboxMessageResponse, error) {
	out := new(DeleteSentboxMessageResponse)
	err := c.cc.Invoke(ctx, "/api.pb.mail.APIService/DeleteSentboxMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	ListInboxMessages(context.Context, *ListInboxMessagesRequest) (*ListInboxMessagesResponse, error)
	ListSentboxMessages(context.Context, *ListSentboxMessagesRequest) (*ListSentboxMessagesResponse, error)
	ReadInboxMessage(context.Context, *ReadInboxMessageRequest) (*ReadInboxMessageResponse, error)
	DeleteInboxMessage(context.Context, *DeleteInboxMessageRequest) (*DeleteInboxMessageResponse, error)
	DeleteSentboxMessage(context.Context, *DeleteSentboxMessageRequest) (*DeleteSentboxMessageResponse, error)
}

// UnimplementedAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (*UnimplementedAPIServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedAPIServiceServer) ListInboxMessages(context.Context, *ListInboxMessagesRequest) (*ListInboxMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInboxMessages not implemented")
}
func (*UnimplementedAPIServiceServer) ListSentboxMessages(context.Context, *ListSentboxMessagesRequest) (*ListSentboxMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSentboxMessages not implemented")
}
func (*UnimplementedAPIServiceServer) ReadInboxMessage(context.Context, *ReadInboxMessageRequest) (*ReadInboxMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadInboxMessage not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteInboxMessage(context.Context, *DeleteInboxMessageRequest) (*DeleteInboxMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInboxMessage not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteSentboxMessage(context.Context, *DeleteSentboxMessageRequest) (*DeleteSentboxMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSentboxMessage not implemented")
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pb.mail.APIService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListInboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInboxMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListInboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pb.mail.APIService/ListInboxMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListInboxMessages(ctx, req.(*ListInboxMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListSentboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSentboxMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListSentboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pb.mail.APIService/ListSentboxMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListSentboxMessages(ctx, req.(*ListSentboxMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ReadInboxMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadInboxMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ReadInboxMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pb.mail.APIService/ReadInboxMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ReadInboxMessage(ctx, req.(*ReadInboxMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteInboxMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInboxMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteInboxMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pb.mail.APIService/DeleteInboxMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteInboxMessage(ctx, req.(*DeleteInboxMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteSentboxMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSentboxMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteSentboxMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.pb.mail.APIService/DeleteSentboxMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteSentboxMessage(ctx, req.(*DeleteSentboxMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.pb.mail.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _APIService_SendMessage_Handler,
		},
		{
			MethodName: "ListInboxMessages",
			Handler:    _APIService_ListInboxMessages_Handler,
		},
		{
			MethodName: "ListSentboxMessages",
			Handler:    _APIService_ListSentboxMessages_Handler,
		},
		{
			MethodName: "ReadInboxMessage",
			Handler:    _APIService_ReadInboxMessage_Handler,
		},
		{
			MethodName: "DeleteInboxMessage",
			Handler:    _APIService_DeleteInboxMessage_Handler,
		},
		{
			MethodName: "DeleteSentboxMessage",
			Handler:    _APIService_DeleteSentboxMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/mail/mail.proto",
}
